name: Elimina issue

on:
  issues:
    types: [unlabeled,closed]
jobs:
  debugUtile:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.5.1
        with:
          project: Prova
          column: ${{ github.event.label.name }}
          repo-token: ${{ secrets.GH_TOKEN }}
          action: delete
