name: Sposta issue nella colonna giusta

on:
  issues:
    types: [opened,edited]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Prova
          column: ${{ github.event.label.name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
